# PLAYER
STARTING_LENGTH = 3

# CNN
LEARNING_RATE = .1
N_INPUT_CHANNELS = 2
BATCH_SIZE = 32
EPSILON_GREEDY = 0.1  # todo
GAMMA = .9

MODELS_DIR = "models"

TRAIN_MODEL = 1

SAVE_MODEL = 1
SAVE_MODEL_BATCH_ITERATIONS = 3000
PRINT_LOSS_BATCH_ITERATIONS = 1000

LOAD_MODEL = 0
LOAD_MODEL_FILE_NAME = "2019-08-11-23-11-53.h5"

# GAME
N_ITERATIONS = 10000000
PYGAME = 1
DISPLAY = 0
RENDER_DELAY = 0.1
NO_DISPLAY_ITERATION_SUMMARY = 20000

GAME_WIDTH = 10
GAME_HEIGHT = 10
N_FOOD = 10

# scores
SCORE_FOOD = 1
SCORE_DEAD = 0
SCORE_KILLING = 0


# todo
# look at EPSILON_GREEDY param
# look at cnn_player.py get_action function! (on/off policy)
