# PLAYER
STARTING_LENGTH = 3

# CNN
LEARNING_RATE = .1
N_INPUT_CHANNELS = 4
BATCH_SIZE = 32
EPSILON_GREEDY = 0  # todo
GAMMA = .9

MODELS_DIR = "models"

TRAIN_MODEL = True

SAVE_MODEL = True
SAVE_MODEL_BATCH_ITERATIONS = 1000

LOAD_MODEL = True
LOAD_MODEL_FILE_NAME = "2019-08-10-22-16-19.h5"

# GAME
DISPLAY = False
RENDER_DELAY = 0.1
NO_DISPLAY_ITERATION_SUMMARY = 5000
GAME_WIDTH = 24
GAME_HEIGHT = 24
N_FOOD = 7

# scores
SCORE_FOOD = 0
SCORE_DEAD = -10
SCORE_KILLING = 100
