LEFT_ACTION = "LEFT_ACTION"
RIGHT_ACTION = "RIGHT_ACTION"
FORWARD_ACTION = "FORWARD_ACTION"
ACTIONS = [FORWARD_ACTION, LEFT_ACTION, RIGHT_ACTION]
N_ACTIONS = len(ACTIONS)

RIGHT = "RIGHT"
LEFT = "LEFT"
UP = "UP"
DOWN = "DOWN"
DIRECTIONS = [UP, RIGHT, LEFT, DOWN]
N_DIRECTIONS = len(DIRECTIONS)

FOOD_MARK = 100
FREE_SQUARE_MARK = 0

SCORE_STR = "SCORE"


# PLAYERS

CNN_PLAYER = "CNN"
NN_PLAYER = "NN"
GREEDY_PLAYER = "GREEDY"
RANDOM_PLAYER = "RANDOM"
MANUAL_PLAYER = "MANUAL"
